name: node_app

on:
  workflow_dispatch:
  push:
    paths:
      - infra/cm/**
    branches:
      - '**'
  pull_request:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest # specify the build machine
    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3
      - # Login into AWS
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - # Login into Amazon ECR
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - # create a build kit builder instance
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - # Build the docker image to push to ECR
        name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.AWS_ECR_URL }}
          docker build -t fiap-fast-food .
          docker tag fiap-fast-food:latest ${{ env.AWS_ECR_URL }}/fiap-fast-food:latest
          docker push ${{ env.AWS_ECR_URL }}/fiap-fast-food:latest
