spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME:tech}
    password: ${DB_PASSWORD:tech_passwd}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        default_schema: produto
        enable_lazy_load_no_trans: true
    show-sql: true
  flyway:
    enabled: true
    schemas: produto
    locations: classpath:db/migration
    baseline-on-migrate: true
