application:
  title: Produto
  version: 1.0

spring:
  main:
    allow-circular-references: true
  profiles:
    active: '@activeProfile@'
  application:
    name: produto
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: produto
        enable_lazy_load_no_trans: true
    show-sql: false
  flyway:
    enabled: false
  devtools:
    add-properties: false
  cache:
    jcache:
      config: classpath:ehcache.xml

server:
  servlet:
    context-path: /api
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
  path: swagger-ui-custom.html
