spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:produto;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS produto;
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  flyway:
    enabled: false
  h2:
    console:
      enabled: true